[workspace]
members = ["."]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.92"
version = "0.1.0"

[workspace.dependencies]
gpui = { git = "https://github.com/berylorg/zed-fork.git", rev = "19ef0796613226c123a3c9047865060e7639f713", default-features = false, features = ["windows-manifest"] }
gpui-scrollbar = { git = "https://github.com/berylorg/gpui-scrollbar.git", rev = "1ca3bef5313117fc8edda88fc7aa2cb66e0cc013" }
gpui-text-input = { git = "https://github.com/berylorg/gpui-text-input.git", rev = "83848233f7e06314454d172053ed05b751231519" }
raw-window-handle = "0.6.2"
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[package]
name = "gpui-settings-window"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gpui.workspace = true
gpui-scrollbar.workspace = true
gpui-text-input.workspace = true
raw-window-handle.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
