[workspace]
members = ["."]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.92"
version = "0.1.0"

[workspace.dependencies]
gpui = { git = "https://github.com/berylorg/zed-fork.git", rev = "b83f38e38839ab1b917febfbbacfbed900e57e09", default-features = false, features = ["windows-manifest"] }
gpui-scrollbar = { git = "https://github.com/berylorg/gpui-scrollbar.git", rev = "ae6302fafa26e5ffea4604b66ff6758c7abf2e0f" }
gpui-text-input = { git = "https://github.com/berylorg/gpui-text-input.git", rev = "975e3d44ee16ba457f31c8364bf5b937791f567b" }
raw-window-handle = "0.6.2"
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }

[package]
name = "gpui-settings-window"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
gpui.workspace = true
gpui-scrollbar.workspace = true
gpui-text-input.workspace = true
raw-window-handle.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
